[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py310"
respect-gitignore = true
extend-exclude = [
    # ROS2 test scripts
    "src/**/test/*.py",

    # explicitly exclude submodules
    "src/doosan-robot2",
    "src/ObjRec_Patient_Mobility",
    "src/zed-ros2-wrapper"
]

[tool.ruff.lint]
extend-select = ["I"] # isort
