variables:
  - &TARGET_FRAME base_link
  - &MAX_TF_AGE 0.05 # seconds

topics:
  - name: /point_cloud
    type: geometry_msgs/msg/PointCloud2
    requires_tf: true
    target_frame: *TARGET_FRAME
    max_tf_age: *MAX_TF_AGE
    
  - name: /pose
    type: geometry_msgs/msg/PoseStamped
    requires_tf: true
    target_frame: *TARGET_FRAME
    max_tf_age: *MAX_TF_AGE

  - name: /chatter
    type: std_msgs/msg/String
    requires_tf: false
