shapes:
  - name: "table_top"
    type: "plane"
    frame_id: "base_link"
    position: [-0.4, -0.4, -0.001]
    orientation: [0.0, 0.0, 0.0, 1.0]
    width: 1.4
    length: 1.4
    thickness: 0.005

  - name: "second_arm"
    type: "cylinder"
    frame_id: "base_link"
    position: [-0.9, 0.0, 0.4]
    orientation: [0.0, 0.0, 0.0, 1.0]
    height: 0.8
    radius: 0.25
