shapes:
  - name: "table_top"
    type: "plane"
    frame_id: "base_link"
    position: [0.56, 0.38, -0.001]
    orientation: [0.0, 0.0, 0.0, 1.0]
    width: 1.360
    length: 0.960
    thickness: 0.005

  - name: "second_arm"
    type: "cylinder"
    frame_id: "base_link"
    position: [0.76, 0.0, 0.4]
    orientation: [0.0, 0.0, 0.0, 1.0]
    height: 0.9
    radius: 0.25
